### ISSUE TITLE
azure baby whiteshark yaml config 

### ISSUE THREAD

**Issue by gms158** [sbenthall/SHARKFin#157]
yaml configuration resulting in market failure

``` yaml 
SIMULATIONS:
- simid: 16
  seed: &seedref16 92975
  rabbitMQHost: &hostref16 10.11.19.4
  rabbitMQqueue: &queueref16 whitesharkqueue16
  ammps_config: &ammpsconfigref16 test_conf.xlsx
  sharkfin:
    save_as: ../../output/whiteshark-babyrunv4-16
    parameters:
      simulation: Attention
      tag: tag
      seed: *seedref16
      popn: 25
      quarters: 8
      runs: 60
      attention: 0.99
      dphm: 20000
      market: ClientRPCMarket
      dividend_growth_rate: 1.0
      dividend_std: 0.011988
      queue: *queueref16
      rhost: *hostref16
      p1: 0.01
      p2: 0.05
      d1: 60
      d2: 60
  ammps:
    ammps_config_file_name: *ammpsconfigref16
    ammps_output_dir: ammps_test_out16
    parameters:
      number: 0
      rabbitMQ-host: *hostref16
      rabbitMQ-queue: *queueref16
      t: true
  ammps_config_gen:
    parameters:
      seed: *seedref16
      name: *ammpsconfigref16
      days: 480
      out-dir: /usr/simulation/
```
