### ISSUE TITLE
type 1 error example in latest run

### ISSUE THREAD

**Issue by gms158** [sbenthall/SHARKFin#165]
Type 1 error example (container 80).

Warning: Agent has risky share > 1.0. Setting to 1. Need to fix solution!
Warning: Agent has risky share > 1.0. Setting to 1. Need to fix solution!
Warning: Agent has risky share > 1.0. Setting to 1. Need to fix solution!
Warning: Agent has risky share > 1.0. Setting to 1. Need to fix solution!
waiting for response...
response received:{'BuyTarget': 1, 'SellTarget': 1, 'ClosingPrice': 1, 'MarketState': 'Stopped: Hit market maker price range, shutting market down. ABC MarketMaker Best Ask and Best Bid is outside range 500009 , 497889 at 2017-10-09 13:05:25.279041\n', 'NextDividend': 1}
The market stopped! Do something!
Ending simulation
Market stopped
Length of values (200) does not match length of index (201)
Lengths:{'buy_macro': 201, 'sell_macro': 201, 'owned': 200, 'total_assets': 200, 'mean_income': 200, 'total_consumption': 200, 'expected_ror': 200, 'expected_std': 200}
Length of values (200) does not match length of index (201)
Lengths:{'buy_macro': 201, 'sell_macro': 201, 'owned': 200, 'total_assets': 200, 'mean_income': 200, 'total_consumption': 200, 'expected_ror': 200, 'expected_std': 200}
Length of values (200) does not match length of index (201)
Lengths:{'buy_macro': 201, 'sell_macro': 201, 'owned': 200, 'total_assets': 200, 'mean_income': 200, 'total_consumption': 200, 'expected_ror': 200, 'expected_std': 200}
Ending the run_any_simulation.py script
Simulation ended
Finished OK for RunConfFromFile test_conf.xlsx ammps_test_out80
finished  80

``` yaml

SIMULATIONS:
- simid: 80
  seed: &seedref80 58067
  rabbitMQHost: &hostref80 10.11.7.4
  rabbitMQqueue: &queueref80 whitesharkqueue80
  ammps_config: &ammpsconfigref80 test_conf.xlsx
  sharkfin:
    save_as: ../../output/whiteshark-babyrun-v6-r2-80
    parameters:
      simulation: Attention
      tag: tag
      seed: *seedref80
      popn: 25
      quarters: 8
      runs: 60
      attention: 0.75
      dphm: 70000
      market: ClientRPCMarket
      dividend_growth_rate: 1.002
      dividend_std: 0.011988
      queue: *queueref80
      rhost: *hostref80
      p1: 0.1
      p2: 0.1
      d1: 60
      d2: 60
  ammps:
    ammps_config_file_name: *ammpsconfigref80
    ammps_output_dir: ammps_test_out80
    parameters:
      number: 0
      rabbitMQ-host: *hostref80
      rabbitMQ-queue: *queueref80
      t: true
  ammps_config_gen:
    parameters:
      seed: *seedref80
      name: *ammpsconfigref80
      days: 480
      out-dir: /usr/simulation/
```
